#! /bin/bash

source config.ini 

## Agile-Ant runs

hdfs dfs -rm -r /AgileAnt/Applications/HiBench/*/Output

### LIR

spark-submit --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/ --deploy-mode cluster --conf spark.yarn.maxAppAttempts=1 --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s --conf spark.agileant.datasetbenefitratio=0.25 --conf spark.default.parallelism=200 --conf spark.sql.shuffle.partitions=200  --class com.intel.hibench.sparkbench.ml.LinearRegressionWithElasticNet --master yarn --num-executors $initialNumberOfExecutors --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --driver-memory $executorMemorySize binaries/sparkbench-assembly-8.0-SNAPSHOT-dist.jar --regParam 0.3 --elasticNetParam 0.8 --maxIter 100 --tol 1E-6 hdfs:/AgileAnt/Applications/HiBench/Linear/Input

### SVM

spark-submit --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/ --deploy-mode cluster --conf spark.yarn.maxAppAttempts=1 --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s --conf spark.agileant.datasetbenefitratio=0.25 --conf spark.default.parallelism=200 --conf spark.sql.shuffle.partitions=200  --class com.intel.hibench.sparkbench.ml.SVMWithSGDExample --master yarn --num-executors $initialNumberOfExecutors --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --driver-memory $executorMemorySize binaries/sparkbench-assembly-8.0-SNAPSHOT-dist.jar --numIterations 100 --storageLevel MEMORY_ONLY --stepSize 1.0 --regParam 0.01 hdfs:/AgileAnt/Applications/HiBench/SVM/Input

### PCA

spark-submit --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/ --deploy-mode cluster --conf spark.yarn.maxAppAttempts=1 --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s --conf spark.agileant.datasetbenefitratio=0.25 --conf spark.default.parallelism=200 --conf spark.sql.shuffle.partitions=200  --class com.intel.hibench.sparkbench.ml.PCAExample --master yarn --num-executors $initialNumberOfExecutors --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --driver-memory $executorMemorySize binaries/sparkbench-assembly-8.0-SNAPSHOT-dist.jar --k 10 --maxResultSize 8g hdfs:/AgileAnt/Applications/HiBench/PCA/Input

### LDA

spark-submit --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/ --deploy-mode cluster --conf spark.yarn.maxAppAttempts=1 --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s --conf spark.agileant.datasetbenefitratio=0.25 --conf spark.default.parallelism=200 --conf spark.sql.shuffle.partitions=200  --class com.intel.hibench.sparkbench.ml.LDAExample --master yarn --num-executors $initialNumberOfExecutors --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --driver-memory $executorMemorySize binaries/sparkbench-assembly-8.0-SNAPSHOT-dist.jar --numTopics 30 --maxIterations 20 --optimizer online --maxResultSize 3g hdfs:/AgileAnt/Applications/HiBench/LDA/Input hdfs:/AgileAnt/Applications/HiBench/LDA/Output

### LR

spark-submit --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/ --deploy-mode cluster --conf spark.yarn.maxAppAttempts=1 --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s --conf spark.agileant.datasetbenefitratio=0.25 --conf spark.default.parallelism=200 --conf spark.sql.shuffle.partitions=200  --class com.intel.hibench.sparkbench.ml.LogisticRegression --master yarn --num-executors $initialNumberOfExecutors --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --driver-memory $executorMemorySize binaries/sparkbench-assembly-8.0-SNAPSHOT-dist.jar hdfs:/AgileAnt/Applications/HiBench/LR/Input

### RF

spark-submit --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/ --deploy-mode cluster --conf spark.yarn.maxAppAttempts=1 --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s --conf spark.agileant.datasetbenefitratio=0.25 --conf spark.default.parallelism=200 --conf spark.sql.shuffle.partitions=200  --class com.intel.hibench.sparkbench.ml.RandomForestClassification --master yarn --num-executors $initialNumberOfExecutors --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --driver-memory $executorMemorySize binaries/sparkbench-assembly-8.0-SNAPSHOT-dist.jar --numTrees 100 --numClasses 2 --featureSubsetStrategy auto --impurity gini --maxDepth 10 --maxBins 32 hdfs:/AgileAnt/Applications/HiBench/RF/Input

### GBT

spark-submit --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/ --deploy-mode cluster --conf spark.yarn.maxAppAttempts=1 --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s --conf spark.agileant.datasetbenefitratio=0.25 --conf spark.default.parallelism=200 --conf spark.sql.shuffle.partitions=200  --class com.intel.hibench.sparkbench.ml.GradientBoostedTree --master yarn --num-executors $initialNumberOfExecutors --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --driver-memory $executorMemorySize binaries/sparkbench-assembly-8.0-SNAPSHOT-dist.jar --numClasses 2 --maxDepth 30 --maxBins 32 --numIterations 20 --learningRate 0.1 hdfs:/AgileAnt/Applications/HiBench/GBT/Input

### ALS

spark-submit --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/ --deploy-mode cluster --conf spark.yarn.maxAppAttempts=1 --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s --conf spark.agileant.datasetbenefitratio=0.25 --conf spark.default.parallelism=200 --conf spark.sql.shuffle.partitions=200  --class com.intel.hibench.sparkbench.ml.ALSExample --master yarn --num-executors $initialNumberOfExecutors --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --driver-memory $executorMemorySize binaries/sparkbench-assembly-8.0-SNAPSHOT-dist.jar --rank 10 --numIterations 15 --implicitPrefs true --numProductBlocks 200 --numUserBlocks 200 --lambda 0.1 hdfs:/AgileAnt/Applications/HiBench/ALS/Input

### KM

spark-submit --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/ --deploy-mode cluster --conf spark.yarn.maxAppAttempts=1 --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s --conf spark.agileant.datasetbenefitratio=0.25 --conf spark.default.parallelism=200 --conf spark.sql.shuffle.partitions=200  --class com.intel.hibench.sparkbench.ml.DenseKMeans --master yarn --num-executors $initialNumberOfExecutors --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --driver-memory $executorMemorySize binaries/sparkbench-assembly-8.0-SNAPSHOT-dist.jar -k 10 --numIterations 100 --storageLevel MEMORY_ONLY --initMode Random hdfs:/AgileAnt/Applications/HiBench/Kmeans/Input/samples

### SPR

spark-submit --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/ --deploy-mode cluster --conf spark.yarn.maxAppAttempts=1 --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s --conf spark.agileant.datasetbenefitratio=0.25 --conf spark.default.parallelism=200 --conf spark.sql.shuffle.partitions=200  --class org.apache.spark.examples.SparkPageRank --master yarn --num-executors $initialNumberOfExecutors --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --driver-memory $executorMemorySize binaries/sparkbench-assembly-8.0-SNAPSHOT-dist.jar hdfs:/AgileAnt/Applications/HiBench/Pagerank/Input/edges hdfs:/AgileAnt/Applications/HiBench/Pagerank/Output 10

### NW

spark-submit --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/ --deploy-mode cluster --conf spark.yarn.maxAppAttempts=1 --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s --conf spark.agileant.datasetbenefitratio=0.25 --conf spark.default.parallelism=200 --conf spark.sql.shuffle.partitions=200  --class com.intel.hibench.sparkbench.graph.nweight.NWeight --master yarn --num-executors $initialNumberOfExecutors --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --driver-memory $executorMemorySize binaries/sparkbench-assembly-8.0-SNAPSHOT-dist.jar hdfs:/AgileAnt/Applications/HiBench/NWeight/Input hdfs:/AgileAnt/Applications/HiBench/NWeight/Output 3 30 200 3 false graphx

### WC

spark-submit --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/ --deploy-mode cluster --conf spark.yarn.maxAppAttempts=1 --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s --conf spark.agileant.datasetbenefitratio=0.25 --conf spark.default.parallelism=200 --conf spark.sql.shuffle.partitions=200  --class com.intel.hibench.sparkbench.micro.ScalaWordCount --master yarn --num-executors $initialNumberOfExecutors --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --driver-memory $executorMemorySize binaries/sparkbench-assembly-8.0-SNAPSHOT-dist.jar hdfs:/AgileAnt/Applications/HiBench/Wordcount/Input hdfs:/AgileAnt/Applications/HiBench/Wordcount/Output

### Sort

spark-submit --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/ --deploy-mode cluster --conf spark.yarn.maxAppAttempts=1 --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s --conf spark.agileant.datasetbenefitratio=0.25 --conf spark.default.parallelism=200 --conf spark.sql.shuffle.partitions=200  --class com.intel.hibench.sparkbench.micro.ScalaSort --master yarn --num-executors $initialNumberOfExecutors --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --driver-memory $executorMemorySize binaries/sparkbench-assembly-8.0-SNAPSHOT-dist.jar hdfs:/AgileAnt/Applications/HiBench/Sort/Input hdfs:/AgileAnt/Applications/HiBench/Sort/Output

### ACON

spark-submit --master yarn --deploy-mode cluster --driver-memory $executorMemorySize --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/ --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.auto.cacher.policy=resourceConstrained --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s --conf spark.agileant.datasetbenefitratio=0.25 --num-executors $initialNumberOfExecutors --jars binaries/cloud9-2.0.1.jar binaries/acon.jar hdfs:/AgileAnt/Applications/Data/ACON/data;


### ADNT 

spark-submit --master yarn --deploy-mode cluster --driver-memory $executorMemorySize --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/ --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.auto.cacher.policy=resourceConstrained --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s --conf spark.agileant.datasetbenefitratio=0.25 --num-executors $initialNumberOfExecutors binaries/adnt.jar hdfs:/AgileAnt/Applications/Data/ADNT/data;



### PFC

spark-submit --master yarn --deploy-mode cluster --driver-memory $executorMemorySize --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/ --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.auto.cacher.policy=resourceConstrained --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s --conf spark.agileant.datasetbenefitratio=0.25 --num-executors $initialNumberOfExecutors binaries/pfc.jar hdfs:/AgileAnt/Applications/Data/PFC/data;


### RM 

spark-submit --master yarn --deploy-mode cluster --driver-memory $executorMemorySize --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/ --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.auto.cacher.policy=resourceConstrained --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s --conf spark.agileant.datasetbenefitratio=0.25 --num-executors $initialNumberOfExecutors binaries/rm.jar hdfs:/AgileAnt/Applications/Data/RM/data/;


### CC

spark-submit --master yarn --deploy-mode cluster --driver-memory $executorMemorySize --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/  --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s  --conf spark.auto.cacher.policy=resourceConstrained --conf spark.agileant.datasetbenefitratio=0.25 --num-executors $initialNumberOfExecutors  --conf spark.yarn.maxAppAttempts=1 --jars binaries/graphframes-0.8.2-spark3.0-s_2.12.jar --class main.connectedComponents binaries/simple-project_2.12-0.1.0-SNAPSHOT.jar hdfs:/AgileAnt/Applications/Data/road-road-usa.mtx;

### LP

spark-submit --master yarn --deploy-mode cluster --driver-memory $executorMemorySize --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/  --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s  --conf spark.auto.cacher.policy=resourceConstrained --conf spark.agileant.datasetbenefitratio=0.25 --num-executors $initialNumberOfExecutors  --conf spark.yarn.maxAppAttempts=1 --jars binaries/graphframes-0.8.2-spark3.0-s_2.12.jar --class main.LabelPropagation binaries/simple-project_2.12-0.1.0-SNAPSHOT.jar hdfs:/AgileAnt/Applications/Data/road-road-usa.mtx;

### PR

spark-submit --master yarn --deploy-mode cluster --driver-memory $executorMemorySize --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/  --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s  --conf spark.auto.cacher.policy=resourceConstrained --conf spark.agileant.datasetbenefitratio=0.25 --num-executors $initialNumberOfExecutors  --conf spark.yarn.maxAppAttempts=1 --jars binaries/graphframes-0.8.2-spark3.0-s_2.12.jar --class main.PageRank binaries/simple-project_2.12-0.1.0-SNAPSHOT.jar hdfs:/AgileAnt/Applications/Data/road-road-usa.mtx;

### SCC

spark-submit --master yarn --deploy-mode cluster --driver-memory $executorMemorySize --executor-cores $numberOfCoresPerExecutor --executor-memory $executorMemorySize --conf spark.eventLog.enabled=true --conf spark.eventLog.dir=hdfs:/AgileAnt/ExecutionLogs/  --conf spark.yarn.archive=hdfs:/AgileAnt/Jars --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --conf spark.dynamicAllocation.maxExecutors=$fullClusterSize --conf spark.dynamicAllocation.schedulerBacklogTimeout=1s --conf spark.dynamicAllocation.sustainedSchedulerBacklogTimeout=1s  --conf spark.auto.cacher.policy=resourceConstrained --conf spark.agileant.datasetbenefitratio=0.25 --num-executors $initialNumberOfExecutors  --conf spark.yarn.maxAppAttempts=1 --jars binaries/graphframes-0.8.2-spark3.0-s_2.12.jar --class main.stronglyConnectedComponents binaries/simple-project_2.12-0.1.0-SNAPSHOT.jar hdfs:/AgileAnt/Applications/Data/road-road-usa.mtx;

